stages:
  - lint
  - typecheck
  - test
  - docs

image: python:3.11-slim

before_script:
  - python -m pip install --upgrade pip
  - pip install ruff mypy pytest sphinx furo

lint:
  stage: lint
  script:
    - ruff check src tests
    - ruff format --check src tests

typecheck:
  stage: typecheck
  script:
    - mypy src

test:
  stage: test
  script:
    - PYTHONPATH=. pytest -q

docs:
  stage: docs
  script:
    - sphinx-build -b html docs/source docs/build
  artifacts:
    when: always
    paths:
      - docs/build
